import { test, expect } from "@playwright/test";
async function login(page,name) {
  await page.goto("/");
  await page.getByRole("button",{name:new RegExp(name)}).click();
  await page.getByLabel("Password",{exact:true}).fill("Demo@1234");
  await page.getByRole("button",{name:"Sign in →",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Your projects",exact:true})).toBeVisible();
}
async function register(page,name,capability,project) {
  await page.getByRole("button",{name:"Agents",exact:true}).click();
  await page.getByRole("button",{name:"+ Register agent",exact:true}).click();
  await page.getByLabel("Agent name",{exact:true}).fill(name);
  await page.getByRole("button",{name:"Continue →",exact:true}).click();
  await page.getByRole("button",{name:new RegExp(capability)}).click();
  await page.getByRole("button",{name:"Continue →",exact:true}).click();
  if(project) {
    await expect(page.getByText("Connection configuration",{exact:true})).toHaveCount(0);
    await page.getByLabel("Search projects").fill(project);
    await page.getByRole("checkbox",{name:new RegExp(project)}).check();
    await expect(page.getByRole("dialog")).toContainText("Residential tower project");
    await page.screenshot({path:"test-results/project-selection.png"});
  }
  await page.getByRole("button",{name:"Continue →",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Review permissions"})).toBeVisible();
  await page.getByRole("button",{name:"Register agent",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Your agent is ready"})).toBeVisible();
  await page.getByRole("button",{name:"Back to agents",exact:true}).click();
  return page.locator(".agent-card").filter({has:page.getByRole("heading",{name,exact:true})});
}
test("Password login, session restore and logout, both administrators, and real OpenFGA actions",async({page})=>{
  const errors=[];page.on("pageerror",error=>errors.push(error.message));
  await page.goto("/");
  await expect(page.getByRole("heading",{name:"Sign in to Northstar"})).toBeVisible();
  await page.screenshot({path:"test-results/login.png",fullPage:true});
  await page.getByRole("button",{name:/Aarav Sharma/}).click();
  await page.getByLabel("Password",{exact:true}).fill("wrong-password");
  await page.getByRole("button",{name:"Sign in →",exact:true}).click();
  await expect(page.getByRole("alert")).toContainText("incorrect");
  await login(page,"Aarav Sharma");
  await page.reload();
  await expect(page.getByRole("heading",{name:"Your projects",exact:true})).toBeVisible();
  await expect(page.getByRole("heading",{name:"Green Heights",exact:true})).toHaveCount(0);
  await page.getByRole("button",{name:"+ Create project",exact:true}).click();
  const humanProject="Cedar Residences "+Date.now();
  await page.getByLabel("Project name",{exact:true}).fill(humanProject);
  await page.getByLabel("Description",{exact:true}).fill("A family residential development in My Homes.");
  await page.getByRole("button",{name:"Create project",exact:true}).click();
  await expect(page.getByRole("heading",{name:humanProject,exact:true})).toBeVisible();
  const reader="Sunrise Assistant "+Date.now();
  const card=await register(page,reader,"Read projects","Sunrise Towers");
  await card.getByRole("button",{name:"View permissions & test access →"}).click();
  await page.getByLabel("Project",{exact:true}).selectOption({label:"Sunrise Towers · assigned"});
  await page.getByRole("button",{name:"Read project",exact:true}).click();
  await expect(page.locator(".decision")).toContainText("Access allowed");
  await page.getByLabel("Project",{exact:true}).selectOption({label:"Lake View · not assigned"});
  await page.getByRole("button",{name:"Read project",exact:true}).click();
  await expect(page.locator(".decision")).toContainText("Access denied");
  await page.screenshot({path:"test-results/read-denied.png",fullPage:true});
  await page.getByRole("button",{name:"Close dialog"}).click();
  const creator="My Homes Creator "+Date.now();
  const creatorCard=await register(page,creator,"Create projects");
  await creatorCard.getByRole("button",{name:"View permissions & test access →"}).click();
  await page.getByLabel("Project name",{exact:true}).fill("Agent Created Cedar "+Date.now());
  await page.getByRole("button",{name:"Create project as agent",exact:true}).click();
  await expect(page.locator(".decision")).toContainText("Access allowed");
  await page.getByLabel("Target organization").selectOption("green-builders");
  await page.getByRole("button",{name:"Create project as agent",exact:true}).click();
  await expect(page.locator(".decision")).toContainText("Access denied");
  await page.getByRole("button",{name:"Close dialog"}).click();
  await page.getByRole("button",{name:"Projects",exact:true}).click();
  await page.getByRole("button",{name:"+ Create project",exact:true}).click();
  const delegatedProject="Delegated Cedar "+Date.now();
  await page.getByLabel("Project name",{exact:true}).fill(delegatedProject);
  await page.getByLabel("Create as",{exact:true}).selectOption({label:creator+" · agent"});
  await page.getByRole("button",{name:"Create project",exact:true}).click();
  await expect(page.getByRole("heading",{name:delegatedProject,exact:true})).toBeVisible();
  await expect(page.locator(".project-card").filter({has:page.getByRole("heading",{name:delegatedProject,exact:true})})).toContainText(creator);
  await page.getByRole("button",{name:"Permissions",exact:true}).click();
  await expect(page.getByRole("cell",{name:"Sunrise Towers",exact:true}).first()).toBeVisible();
  await page.screenshot({path:"test-results/permissions.png",fullPage:true});
  await page.getByRole("button",{name:"Sign out",exact:true}).click();
  await page.reload();
  await expect(page.getByRole("heading",{name:"Sign in to Northstar"})).toBeVisible();

  await login(page,"Meera Nair");
  await expect(page.getByRole("heading",{name:"Sunrise Towers",exact:true})).toHaveCount(0);
  await expect(page.getByRole("heading",{name:"Green Heights",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"+ Create project",exact:true}).click();
  await page.getByLabel("Project name",{exact:true}).fill("Green Gardens "+Date.now());
  await page.getByRole("button",{name:"Create project",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Green Builders");
  const greenCard=await register(page,"Green Builders Creator "+Date.now(),"Create projects");
  await greenCard.getByRole("button",{name:"View permissions & test access →"}).click();
  await page.getByRole("button",{name:"Create project as agent",exact:true}).click();
  await expect(page.locator(".decision")).toContainText("Access allowed");
  await page.getByLabel("Target organization").selectOption("my-homes");
  await page.getByRole("button",{name:"Create project as agent",exact:true}).click();
  await expect(page.locator(".decision")).toContainText("Access denied");
  await page.getByRole("button",{name:"Close dialog"}).click();
  await page.getByRole("button",{name:"Sign out",exact:true}).click();
  await login(page,"Riya Patel");
  await expect(page.getByRole("heading",{name:"Sunrise Towers",exact:true})).toBeVisible();
  await expect(page.getByRole("heading",{name:"Lake View",exact:true})).toHaveCount(0);
  await expect(page.getByRole("button",{name:"+ Create project",exact:true})).toHaveCount(0);
  await page.getByRole("button",{name:"Agents",exact:true}).click();
  await expect(page.getByRole("button",{name:"+ Register agent",exact:true})).toHaveCount(0);
  expect(errors).toEqual([]);
});
test("Narrow screen keeps login usable", async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto("/");
  await expect(page.getByRole("heading",{name:"Sign in to Northstar"})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
});
