import { useState } from "react";
import { api } from "./api";

export function Dialog({ title, subtitle, close, children, footer }) {
  return <div className="overlay" onClick={e=>{if(e.target===e.currentTarget)close();}}><section className="dialog" role="dialog" aria-modal="true" aria-label={title}><header><div><span className="eyebrow">NORTHSTAR WORKSPACE</span><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="close" aria-label="Close dialog" onClick={close}>×</button></header>{children}{footer&&<footer>{footer}</footer>}</section></div>;
}
export function Decision({ result }) {
  if(!result)return null;
  return <section className={"decision "+(result.allowed?"allow":"deny")} aria-live="polite"><b>{result.allowed?"✓ Access allowed":"× Access denied"} by OpenFGA</b><p>{result.project?'Project: '+result.project.name:result.message??""}</p><details><summary>See authorization checks</summary>{result.checks?.map((c,i)=><div className="check" key={i}><span>{c.allowed?"✓":"×"}</span><code>{c.user} → {c.relation} → {c.object}</code></div>)}</details></section>;
}
export function Registration({ org, projects, close, saved }) {
  const [step,setStep]=useState(0),[name,setName]=useState(""),[type,setType]=useState("READ"),[selected,setSelected]=useState([]),[search,setSearch]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[copied,setCopied]=useState(false);
  const chosen=projects.filter(p=>selected.includes(p.id));
  async function register() {
    setBusy(true);setError("");
    try{const data=await api("/agents",{method:"POST",body:JSON.stringify({name,type,organizationId:org.id,projectIds:type!=="CREATE"?selected:[]})});setResult(data);void saved();}
    catch(err){setError(err.message);}finally{setBusy(false);}
  }
  async function copy(){
    try{await navigator.clipboard.writeText(JSON.stringify(result.mcpConfiguration,null,2));setCopied(true);}catch{setError("Copy is unavailable. Select the configuration text and copy it manually.");}
  }
  const steps=["Agent details","Choose capability","Assign access","Review"];
  const valid=step===0?!!name.trim():step===2&&type!=="CREATE"?selected.length>0:true;
  if(result)return <Dialog title="Your agent is ready" subtitle="Permissions have been saved and checked by OpenFGA." close={close} footer={<button className="primary" onClick={close}>Back to agents</button>}><div className="dialog-body"><div className="success-icon">✓</div><h3>{result.agent.name}</h3><p>{type!=="CREATE"?(type==="UPDATE"?"Can read and update ":"Can read ")+chosen.map(p=>p.name).join(", "):"Can create projects"} in <b>{org.name}</b>.</p><div className="info-banner">Next: open this agent's permissions to test an allowed and a denied action.</div><details className="connection-details"><summary>Connection configuration · for the MCP client</summary><p>In the built-in MCP client, select this agent and connect. This configuration is only needed for external MCP clients.</p><label>Connection configuration<textarea readOnly value={JSON.stringify(result.mcpConfiguration,null,2)}/></label><button className="secondary" onClick={copy}>{copied?"Copied ✓":"Copy configuration"}</button><p className="muted">The API key is shown only here. Save it before closing if you plan to connect later.</p></details>{error&&<p className="error">{error}</p>}</div></Dialog>;
  return <Dialog title="Register an agent" subtitle={"Create an agent for "+org.name} close={()=>{if(!busy)close();}} footer={<><button className="secondary" disabled={busy} onClick={()=>step?setStep(step-1):close()}>{step?"Back":"Cancel"}</button>{step<3?<button className="primary" disabled={!valid} onClick={()=>setStep(step+1)}>Continue →</button>:<button className="primary" disabled={busy} onClick={register}>{busy?"Registering…":"Register agent"}</button>}</>}>
    <ol className="steps">{steps.map((s,i)=><li className={i===step?"current":i<step?"done":""} key={s}><span>{i<step?"✓":i+1}</span>{s}</li>)}</ol>
    <div className="dialog-body">{step===0&&<><h3>What should we call your agent?</h3><p>A clear name helps your team recognize its purpose.</p><label>Agent name<input autoFocus value={name} maxLength={150} onChange={e=>setName(e.target.value)} placeholder="e.g. Sunrise Project Assistant"/></label><div className="locked"><small>ORGANIZATION</small><b>{org.name}</b><span>From your signed-in account</span></div></>}
    {step===1&&<><h3>What can this agent do?</h3><p>Choose the tool permission this agent needs.</p><div className="capabilities">{[["READ","◉","Read projects","View details of projects you explicitly select."],["CREATE","+","Create projects","Create new projects within "+org.name+"."],["UPDATE","↻","Update projects","Read and update only the projects you explicitly select."]].map(([value,icon,title,desc])=><button aria-pressed={type===value} className={type===value?"selected":""} key={value} onClick={()=>setType(value)}><span className="agent-symbol">{icon}</span><b>{title}</b><p>{desc}</p></button>)}</div></>}
    {step===2&&<><h3>{type!=="CREATE"?type==="UPDATE"?"Which projects can this agent update?":"Which projects can this agent read?":"Confirm the organization boundary"}</h3><p>{type!=="CREATE"?"Only selected projects will be available. All other projects remain inaccessible.":"This agent can create projects only inside "+org.name+"."}</p>{type!=="CREATE"?<><label>Search projects<input placeholder="Search by project name…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="selection-count">{selected.length} project{selected.length===1?"":"s"} selected</div><div className="project-picker">{projects.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())).map(p=><label key={p.id} className={selected.includes(p.id)?"picked":""}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(ids=>ids.includes(p.id)?ids.filter(id=>id!==p.id):[...ids,p.id])}/><span><b>{p.name}</b><small>{p.description||"No description yet."}</small><em>{p.organizationName}</em></span><span className="selection-state">{selected.includes(p.id)?"Selected":"Not selected"}</span></label>)}</div>{!projects.length&&<div className="empty">Create a project before registering a read agent.</div>}</>:<div className="scope-preview"><span>✦</span><b>{name}</b><span>→</span><b>Create projects</b><span>→</span><b>{org.name}</b></div>}</>}
    {step===3&&<><h3>Review permissions</h3><p>Make sure this is the access you want to grant.</p><dl className="review"><dt>Agent</dt><dd>{name}</dd><dt>Organization</dt><dd>{org.name}</dd><dt>Tool permission</dt><dd>{type!=="CREATE"?(type==="UPDATE"?"Read and update projects":"Read project details"):"Create projects"}</dd><dt>Project access</dt><dd>{type!=="CREATE"?chosen.map(p=><span className="chip" key={p.id}>{p.name}</span>):"New projects in "+org.name+" only"}</dd></dl><div className="info-banner">OpenFGA checks your authority before creating these permissions.</div></>}
    {error&&<p className="error" role="alert">{error}</p>}</div>
  </Dialog>;
}
export function ProjectForm({ org, agents, close, saved }) {
  const [name,setName]=useState(""),[description,setDescription]=useState(""),[agentId,setAgentId]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(e){
    e.preventDefault();setBusy(true);setError("");
    try{const result=await api(agentId?"/agents/"+agentId+"/projects":"/projects",{method:"POST",body:JSON.stringify({name,description,organizationId:org.id})});await saved(result);}
    catch(err){setError(err.message);}finally{setBusy(false);}
  }
  return <Dialog title="Create a project" subtitle={org.name} close={()=>{if(!busy)close();}}><form className="dialog-body form-stack" onSubmit={submit}><label>Project name<input value={name} autoFocus required maxLength={150} onChange={e=>setName(e.target.value)} placeholder="e.g. Cedar Residences"/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is this project about?"/></label><label>Create as<select aria-label="Create as" value={agentId} onChange={e=>setAgentId(e.target.value)}><option value="">Me · signed-in administrator</option>{agents.filter(a=>a.type==="CREATE"&&a.status==="ACTIVE").map(a=><option key={a.id} value={a.id}>{a.name} · agent</option>)}</select></label><div className="locked"><small>ORGANIZATION</small><b>{org.name}</b><span>{agentId?"OpenFGA checks your access to this agent, its tool, and this organization.":"OpenFGA checks your project creation permission."}</span></div>{error&&<p role="alert" className="error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?"Creating…":"Create project"}</button></form></Dialog>;
}
export function AgentInspector({ agent, projects, close, refresh }) {
  const [projectId,setProjectId]=useState(projects[0]?.id??""),[target,setTarget]=useState(agent.organizationId),[name,setName]=useState("Demo project"),[result,setResult]=useState(null),[busy,setBusy]=useState(false);
  async function test() {
    setBusy(true);setResult(null);
    try{const data=await api(agent.type!=="CREATE"?"/agents/"+agent.id+"/projects/"+projectId:"/agents/"+agent.id+"/projects",
      agent.type!=="CREATE"?(agent.type==="UPDATE"?{method:"PATCH",body:JSON.stringify({description:name})}:{}):{method:"POST",body:JSON.stringify({name,organizationId:target})});setResult(data);}
    catch(err){setResult(err.body??{message:err.message});}finally{setBusy(false);void refresh();}
  }
  return <Dialog title={agent.name} subtitle="Permissions and access test" close={close}><div className="dialog-body"><dl className="review"><dt>Organization</dt><dd>{agent.organizationName}</dd><dt>Tools</dt><dd>{agent.tools.map(t=>t.name).join(", ")}</dd><dt>Project access</dt><dd>{agent.type!=="CREATE"?agent.projects.map(p=><span key={p.id} className="chip">{p.name}</span>):"Create in "+agent.organizationName}</dd></dl><hr/><h3>Try an action</h3><p>Run a real request as this agent. OpenFGA checks every permission.</p>
  {agent.type!=="CREATE"?<label>Project<select aria-label="Project" value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}{agent.projects.some(a=>a.id===p.id)?" · assigned":" · not assigned"}</option>)}</select></label>:<div className="form-stack"><label>Project name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Target organization<select aria-label="Target organization" value={target} onChange={e=>setTarget(e.target.value)}><option value="my-homes">My Homes</option><option value="green-builders">Green Builders</option></select></label><p className="muted">A successful test creates a project. Choose the other organization to demonstrate denied access.</p></div>}
  {agent.type==="UPDATE"&&<label>New description<input value={name} onChange={e=>setName(e.target.value)}/></label>}<button className="primary test-button" disabled={busy||(agent.type!=="CREATE"?!projectId:!name.trim())} onClick={test}>{busy?"Checking…":agent.type!=="CREATE"?(agent.type==="UPDATE"?"Update project":"Read project"):"Create project as agent"}</button><Decision result={result}/></div></Dialog>;
}
